"""Initial MySQL schema

Revision ID: d932e979a1b1
Revises: 
Create Date: 2026-08-23 20:37:52.049195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd932e979a1b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('technology_transfers',
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=200), nullable=False),
    sa.Column('program', sa.String(length=200), nullable=False),
    sa.Column('deployment_date', sa.Date(), nullable=False),
    sa.Column('system_type', sa.String(length=100), nullable=False),
    sa.Column('usage_status', sa.String(length=50), nullable=False),
    sa.Column('user_trained', sa.Integer(), nullable=False),
    sa.Column('partner_institution', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('technology_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technology_transfers')
    op.drop_table('users')
    # ### end Alembic commands ###
